### PR TITLE
Unwrap django lazy objects in mutation resolvers

### PR DESCRIPTION
**Pull request by ryanprobus**
## Description

* Django lazy objects have a proxy `__iter__` method that causes them to be considered iterables even if the wrapped object isn't. This causes errors when calling list on the lazy object. Avoid this by checking and unwrapping any lazy objects. A lazy object could be passed to these mutation resolvers if accessing the django request's user.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* [Django LazyObject is not considered in mutation resolvers](https://github.com/strawberry-graphql/strawberry-graphql-django/issues/333)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by bellini666** [comment]
The changes look great!

Can we have a test for it? Just to avoid that from regressing in the future for whatever reason :)

**Comment by ryanprobus** [comment]
@bellini666 I am not familiar with the pyright issues that are reported by the `Run Tests / Typing` check. To me, they seem unrelated to this change. Is this test known to be fragile? I didn't dive into it, but I am guessing it just reports issues on any files with diff in the PR?

**Comment by bellini666** [comment]
> @bellini666 I am not familiar with the pyright issues that are reported by the `Run Tests / Typing` check. To me, they seem unrelated to this change. Is this test known to be fragile? I didn't dive into it, but I am guessing it just reports issues on any files with diff in the PR?

Indeed they are currently not your fault =P. It just happened to a new version of pyright to be released while this PR was opened, and it did have some regressions in our code which I fixed in https://github.com/strawberry-graphql/strawberry-graphql-django/commit/aed240e9e2ae054c065a04cd4817f68ba2c14524

You can ignore those or just merge/rebase on top of the current main branch.

Btw, the PR is still marked as draft. Is there anything missing or can I review it?

**Comment by bellini666** [comment]
@ryanprobus taking a look at your PR, maybe some of the pyright issues are due to your PR. More specifically, the issues inside `mutations/resolvers.py`

The reason is that `instance = instance.__reduce__()[1][0]` isn't typed in a way that pyright would know that it would be the instance and is being interpreted as `Unknown`. You can `instance = cast(_M, instance.__reduce__()[1][0])` to avoid that in this case

**Comment by bellini666** [comment]
Hi @ryanprobus ,

pyright still thinks that the instance. I checked out your branch and the issue is that the function itself is not typed (because the overloads are)

You might want to change it from:

```python
@transaction.atomic
def update(
    info,
    instance,
    data,
    *,
    full_clean: bool | FullCleanOptions = True,
    pre_save_hook: Callable[[_M], None] | None = None,
):
```

to:

```python
@transaction.atomic
def update(
    info: Info,
    instance: _M | Iterable[_M],
    data: dict[str, Any],
    *,
    full_clean: bool | FullCleanOptions = True,
    pre_save_hook: Callable[[_M], None] | None = None,
):
```

That should fix everything and IMO the patch is ready to be merged

**Comment by bellini666** [comment]
Hey @ryanprobus ,

I took the liberty of updating your PR and fixing the remaining typing issues.

I removed its "Draft" status because I believe it is ready to be merged.

Is there anything else missing in here? Or can I merge it as soon as the tests pass?

**Comment by ryanprobus** [comment]
@bellini666 Its all good to go if you it looks good to you. Thanks for taking a look at the pyright issues.

**Review by bellini666 — APPROVED** [review]

**Pull request merged**
