### PR TITLE
Fix mutations and filtering for when using strawberry-graphql >=0.132.1

### PR DESCRIPTION
**Pull request by jkimbo**
## Description

The [v0.132.1](https://github.com/strawberry-graphql/strawberry/releases/tag/0.132.1) release of strawberry-graphql broke mutations and filtering because it introduced the concept of "basic fields" which skip calling resolvers in certain circumstances. Strawberry-Django doesn't use `base_resolver` for it's custom fields but it does define custom resolvers without implementing the `is_basic_field` property and so the custom resolvers were not longer being called. This PR makes sure that the custom Strawberry Django fields are never treated as "basic" by Strawberry.

It also fixes some tests that were instantiated without keyword arguments. Keyword arguments were required from [v0.128.0](https://github.com/strawberry-graphql/strawberry/releases/tag/0.132.1) of Strawberry.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* fixes https://github.com/strawberry-graphql/strawberry-graphql-django/issues/182

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by g-as** [comment]
That's great, thanks!

**Review by illia-v — APPROVED** [review]
@jkimbo thanks!

This fixes tests in a project that strawberry-graphql 0.132.1 could break.

**Comment by bellini666** [comment]
Hey @jkimbo . PR looks great! :)
Just need to resolve the conflicts in poetry.lock.

Also, since this will fix the issue from v0.132.1, maybe we should alson unpin the restriction in here?

**Comment by jkimbo** [comment]
> Also, since this will fix the issue from v0.132.1, maybe we should alson unpin the restriction in here?

Good point, I've removed the restriction now.

**Review by bellini666 — APPROVED** [review]

**Pull request merged**
