### PR TITLE
Update django version from 4.2b1 to 4.2rc1

### PR DESCRIPTION
**Pull request by kwongtn**
## Description
Update test django version from 4.2b1 to 4.2rc1

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by bellini666** [comment]
@kwongtn any idea why the apt install is failing?

Maybe instead of using `gh-action-apt-install`, which apparently has some cache issues, run `apt install <packages>` directly?

**Comment by kwongtn** [comment]
> @kwongtn any idea why the apt install is failing?
> 
> Maybe instead of using `gh-action-apt-install`, which apparently has some cache issues, run `apt install <packages>` directly?

It seems that it is not a cache issue, rather an issue with the apt repository.
I've also tried using your method, but to no avail. Will be trying out fixes.

**Comment by bellini666** [comment]
@kwongtn also, Django 4.2 got released today. You can use it directly now

**Comment by bellini666** [comment]
@kwongtn django 4.2 has been released in a while now. Do you want to update this PR to use its final version instead?

**Comment by kwongtn** [comment]
@bellini666 many apologies
I was travelling when django 4.2 got released and totally forgot about it 😅
Thanks for the ping 😁

Will be closing this ticket in favor of:
- https://github.com/strawberry-graphql/strawberry-graphql-django/pull/253

**Pull request closed without merging**
