### PR TITLE
make pk argument required when querying single object

### PR DESCRIPTION
**Pull request by stygmate**
It's just a one line correction to make pk argument required when querying a single django object

edit: and test fot required pk argument

### CODE REVIEW

**Comment by patrick91** [comment]
@stygmate looks good to me, can you update the tests? :)

**Comment by stygmate** [comment]
> @stygmate looks good to me, can you update the tests? :)

Hi the test are not failing because of my modifications. Looks like a error in creation of docker image. Tests are ok my side. But if you want I can add a test to verify that the field is actually required.

**Comment by patrick91** [comment]
> > @stygmate looks good to me, can you update the tests? :)
> 
> Hi the test are not failing because of my modifications. Looks like a error in creation of docker image. Tests are ok my side. But if you want I can add a test to verify that the field is actually required.

yes, let's add that! so we don't get any regression 😊

**Comment by stygmate** [comment]
@patrick91 the ugly pre-commit.ci was annoying me ;) but seems ok now !

**Review by patrick91 — APPROVED** [review]
Looks great! I'll leave the final review to @bellini666 😊

**Review by bellini666 — APPROVED** [review]

**Comment by bellini666** [comment]
LGTM 👍🏼

**Pull request merged**
